### ISSUE TITLE
Trying to get one of the boards you made

### ISSUE THREAD

**Issue by davidmckay01** [Kreeblah/SidewinderToUSBV2#2]
Found your Sidewinder Pro to USB card in the Descent BB, but couldn't get through the registration questions.  I'd like to purchase one of your boards, would you let me know how to do so?   david (((at))) mckaygroup dot ((com)).  Thanks in advance.

**Comment by Kreeblah** [comment]
I just sent you an e-mail, so I'm going to close this.  Please feel free to reopen it if you don't see my e-mail.

Thanks!
