### ISSUE TITLE
buy them

### ISSUE THREAD

**Issue by Soliver84** [Kreeblah/SidewinderToUSBV2#4]
Hello I read here:
Alexhttps://www.descentbb.net/viewtopic.php?p=389914#p389914

That you still have some if you still have 2 pieces, I would like to buy them, starting with the best firmware.
I live in Germany and would of course pay for the shipping. PayPal.

Thaks
Alex

**Comment by Kreeblah** [comment]
Hi there!

I do still have some, but unfortunately I had to stop shipping to the EU last year.  The new rule that took effect on 1 July 2021 requires that any packages sent to the EU have VAT already collected by a registered entity, and the paperwork involved in registering to collect VAT on behalf of the EU doesn't really make sense for me.

That said, if you contact rage76 in that thread, he's located in Germany, and may have some left.

Thanks!

**Comment by Soliver84** [comment]
Unfortunately I don't have access to the forum because I can't manage the security question.

If you send it as a gift or test board, no tax will be charged.

or you can ask the user for me. please i need your help

Thanks
